// <auto-generated />
using System;
using BlogPersonal.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlogPersonal.Infrastructure.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20251118200905_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlogPersonal.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Detalle")
                        .HasColumnType("text");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("BlogPersonal.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("BlogPersonal.Domain.Entities.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorId")
                        .HasColumnType("integer");

                    b.Property<int?>("ComentarioPadreId")
                        .HasColumnType("integer");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EstadoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("ComentarioPadreId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("PostId");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("BlogPersonal.Domain.Entities.EstadoComentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EstadosComentario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Pendiente"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Aprobado"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Rechazado"
                        });
                });

            modelBuilder.Entity("BlogPersonal.Domain.Entities.EstadoPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EstadosPost");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Borrador"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Publicado"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Archivado"
                        });
                });

            modelBuilder.Entity("BlogPersonal.Domain.Entities.Etiqueta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Etiquetas");
                });

            modelBuilder.Entity("BlogPersonal.Domain.Entities.Idioma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Idiomas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "es",
                            Nombre = "Español"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "en",
                            Nombre = "Inglés"
                        });
                });

            modelBuilder.Entity("BlogPersonal.Domain.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorId")
                        .HasColumnType("integer");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EstadoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaPublicacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdiomaId")
                        .HasColumnType("integer");

                    b.Property<bool>("PermitirComentarios")
                        .HasColumnType("boolean");

                    b.Property<string>("Resumen")
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Vistas")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("IdiomaId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("BlogPersonal.Domain.Entities.PostCategoria", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.HasKey("PostId", "CategoriaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("PostCategorias");
                });

            modelBuilder.Entity("BlogPersonal.Domain.Entities.PostEtiqueta", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.Property<int>("EtiquetaId")
                        .HasColumnType("integer");

                    b.HasKey("PostId", "EtiquetaId");

                    b.HasIndex("EtiquetaId");

                    b.ToTable("PostEtiquetas");
                });

            modelBuilder.Entity("BlogPersonal.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Acceso total al sistema",
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Puede crear y gestionar sus propios posts",
                            Nombre = "Autor"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Puede comentar",
                            Nombre = "Usuario"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Solo lectura",
                            Nombre = "Visitante"
                        });
                });

            modelBuilder.Entity("BlogPersonal.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("BlogPersonal.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("BlogPersonal.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BlogPersonal.Domain.Entities.Comentario", b =>
                {
                    b.HasOne("BlogPersonal.Domain.Entities.Usuario", "Autor")
                        .WithMany("Comentarios")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogPersonal.Domain.Entities.Comentario", "ComentarioPadre")
                        .WithMany("Respuestas")
                        .HasForeignKey("ComentarioPadreId");

                    b.HasOne("BlogPersonal.Domain.Entities.EstadoComentario", "Estado")
                        .WithMany("Comentarios")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogPersonal.Domain.Entities.Post", "Post")
                        .WithMany("Comentarios")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("ComentarioPadre");

                    b.Navigation("Estado");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("BlogPersonal.Domain.Entities.Post", b =>
                {
                    b.HasOne("BlogPersonal.Domain.Entities.Usuario", "Autor")
                        .WithMany("Posts")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogPersonal.Domain.Entities.EstadoPost", "Estado")
                        .WithMany("Posts")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogPersonal.Domain.Entities.Idioma", "Idioma")
                        .WithMany("Posts")
                        .HasForeignKey("IdiomaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Estado");

                    b.Navigation("Idioma");
                });

            modelBuilder.Entity("BlogPersonal.Domain.Entities.PostCategoria", b =>
                {
                    b.HasOne("BlogPersonal.Domain.Entities.Categoria", "Categoria")
                        .WithMany("PostCategorias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogPersonal.Domain.Entities.Post", "Post")
                        .WithMany("PostCategorias")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("BlogPersonal.Domain.Entities.PostEtiqueta", b =>
                {
                    b.HasOne("BlogPersonal.Domain.Entities.Etiqueta", "Etiqueta")
                        .WithMany("PostEtiquetas")
                        .HasForeignKey("EtiquetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogPersonal.Domain.Entities.Post", "Post")
                        .WithMany("PostEtiquetas")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etiqueta");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("BlogPersonal.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("BlogPersonal.Domain.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("BlogPersonal.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("PostCategorias");
                });

            modelBuilder.Entity("BlogPersonal.Domain.Entities.Comentario", b =>
                {
                    b.Navigation("Respuestas");
                });

            modelBuilder.Entity("BlogPersonal.Domain.Entities.EstadoComentario", b =>
                {
                    b.Navigation("Comentarios");
                });

            modelBuilder.Entity("BlogPersonal.Domain.Entities.EstadoPost", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("BlogPersonal.Domain.Entities.Etiqueta", b =>
                {
                    b.Navigation("PostEtiquetas");
                });

            modelBuilder.Entity("BlogPersonal.Domain.Entities.Idioma", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("BlogPersonal.Domain.Entities.Post", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("PostCategorias");

                    b.Navigation("PostEtiquetas");
                });

            modelBuilder.Entity("BlogPersonal.Domain.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("BlogPersonal.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
